// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"gitee.com/flycash/notification-platform/internal/service/notification/repository"
	"gitee.com/flycash/notification-platform/internal/service/notification/repository/dao"
	"gitee.com/flycash/notification-platform/internal/service/notification/service"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitService(db *gorm.DB) NotificationService {
	error2 := initTables(db)
	notificationDAO := dao.NewNotificationDAO(db)
	notificationRepository := repository.NewNotificationRepository(notificationDAO)
	notificationService := service.NewNotificationService(notificationRepository)
	iocNotificationService := NotificationService{
		ignoredInitTablesErr: error2,
		Svc:                  notificationService,
	}
	return iocNotificationService
}

// wire.go:

var notificationServiceProviderSet = wire.NewSet(dao.NewNotificationDAO, repository.NewNotificationRepository, service.NewNotificationService)

type NotificationService struct {
	ignoredInitTablesErr error // 必须放在第一个
	Svc                  service.NotificationService
}

func initTables(db *gorm.DB) error {
	return dao.InitTables(db)
}
