// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"gitee.com/flycash/notification-platform/internal/service/provider/internal/repository"
	"gitee.com/flycash/notification-platform/internal/service/provider/internal/repository/dao"
	"gitee.com/flycash/notification-platform/internal/service/provider/internal/service"
	"github.com/ego-component/egorm"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitModule(db *egorm.Component, encrytKey string) Module {
	error2 := initTables(db)
	providerDAO := dao.NewProviderDAO(db, encrytKey)
	providerRepository := repository.NewProviderRepository(providerDAO)
	providerService := service.NewProviderService(providerRepository)
	service2 := convert(providerService)
	module := Module{
		ignoredInitTablesErr: error2,
		Svc:                  service2,
	}
	return module
}

// wire.go:

var providerSet = wire.NewSet(dao.NewProviderDAO, repository.NewProviderRepository, service.NewProviderService)

func convert(svc service.ProviderService) Service {
	return svc.(Service)
}

func initTables(db *egorm.Component) error {
	return dao.InitTables(db)
}
