// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"gitee.com/flycash/notification-platform/internal/service/notification"
	"gitee.com/flycash/notification-platform/internal/test/ioc"
)

// Injectors from wire.go:

func InitNotificationService() notification.Service {
	v := ioc.InitDB()
	sonyflake := ioc.InitIDGenerator()
	module := notification.InitModule(v, sonyflake)
	v2 := module.Svc
	return v2
}
