// Code generated by MockGen. DO NOT EDIT.
// Source: ./audit.go
//
// Generated by this command:
//
//	mockgen -source=./audit.go -destination=../../mocks/audit.mock.go -package=auditmocks -typed AuditService
//

// Package auditmocks is a generated GoMock package.
package auditmocks

import (
	context "context"
	reflect "reflect"

	domain "gitee.com/flycash/notification-platform/internal/service/audit/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditService is a mock of AuditService interface.
type MockAuditService struct {
	ctrl     *gomock.Controller
	recorder *MockAuditServiceMockRecorder
	isgomock struct{}
}

// MockAuditServiceMockRecorder is the mock recorder for MockAuditService.
type MockAuditServiceMockRecorder struct {
	mock *MockAuditService
}

// NewMockAuditService creates a new mock instance.
func NewMockAuditService(ctrl *gomock.Controller) *MockAuditService {
	mock := &MockAuditService{ctrl: ctrl}
	mock.recorder = &MockAuditServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditService) EXPECT() *MockAuditServiceMockRecorder {
	return m.recorder
}

// CreateAudit mocks base method.
func (m *MockAuditService) CreateAudit(ctx context.Context, req domain.Audit) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAudit", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAudit indicates an expected call of CreateAudit.
func (mr *MockAuditServiceMockRecorder) CreateAudit(ctx, req any) *MockAuditServiceCreateAuditCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAudit", reflect.TypeOf((*MockAuditService)(nil).CreateAudit), ctx, req)
	return &MockAuditServiceCreateAuditCall{Call: call}
}

// MockAuditServiceCreateAuditCall wrap *gomock.Call
type MockAuditServiceCreateAuditCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuditServiceCreateAuditCall) Return(arg0 int64, arg1 error) *MockAuditServiceCreateAuditCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuditServiceCreateAuditCall) Do(f func(context.Context, domain.Audit) (int64, error)) *MockAuditServiceCreateAuditCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuditServiceCreateAuditCall) DoAndReturn(f func(context.Context, domain.Audit) (int64, error)) *MockAuditServiceCreateAuditCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
