// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"gitee.com/flycash/notification-platform/internal/service/backup/internal/audit"
	template2 "gitee.com/flycash/notification-platform/internal/service/backup/internal/template"
	"gitee.com/flycash/notification-platform/internal/service/provider"
	"gitee.com/flycash/notification-platform/internal/test/ioc"
)

// Injectors from wire.go:

func InitChannelTemplateService(providerSvc provider.Service, auditSvc audit.Service) template2.Service {
	db := ioc.InitDB()
	module := template2.InitModule(db, providerSvc, auditSvc)
	service := module.Svc
	return service
}
