// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"gitee.com/flycash/notification-platform/internal/repository"
	"gitee.com/flycash/notification-platform/internal/repository/dao"
	txnotification2 "gitee.com/flycash/notification-platform/internal/service/backup/tx_notification"
	"gitee.com/flycash/notification-platform/internal/service/config"
	"gitee.com/flycash/notification-platform/internal/service/notification"
	"gitee.com/flycash/notification-platform/internal/test/ioc"
)

// Injectors from wire.go:

func InitTxNotificationService(notificationModule notification.Module, configModule config.Module) *notification.TxNotificationServiceV1 {
	v := ioc.InitDB()
	txNotificationDAO := dao.NewTxNotificationDAO(v)
	txNotificationRepository := repository.NewTxNotificationRepository(txNotificationDAO)
	v2 := notificationModule.Svc
	v3 := configModule.Svc
	builder := txnotification2.InitRetryServiceBuilder()
	cmdable := ioc.InitRedis()
	client := txnotification2.InitDlickClient(cmdable)
	txNotificationServiceV1 := notification.NewTxNotificationService(txNotificationRepository, v2, v3, builder, client)
	return txNotificationServiceV1
}
