// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package template

import (
	"gitee.com/flycash/notification-platform/internal/service/audit"
	"gitee.com/flycash/notification-platform/internal/service/provider"
	"gitee.com/flycash/notification-platform/internal/service/template/internal/repository"
	"gitee.com/flycash/notification-platform/internal/service/template/internal/repository/dao"
	"gitee.com/flycash/notification-platform/internal/service/template/internal/service"
	"github.com/ego-component/egorm"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitModule(db *egorm.Component, providerSvc provider.Service, auditsvc audit.Service) Module {
	error2 := initTables(db)
	channelTemplateDAO := dao.NewChannelTemplateDAO(db)
	channelTemplateRepository := repository.NewChannelTemplateRepository(channelTemplateDAO)
	channelTemplateService := service.NewChannelTemplateService(channelTemplateRepository, providerSvc, auditsvc)
	templateService := convert(channelTemplateService)
	module := Module{
		ignoredInitTablesErr: error2,
		Svc:                  templateService,
	}
	return module
}

// wire.go:

var ProviderSet = wire.NewSet(dao.NewChannelTemplateDAO, repository.NewChannelTemplateRepository, service.NewChannelTemplateService)

func convert(svc service.ChannelTemplateService) Service {
	return svc.(Service)
}

func initTables(db *egorm.Component) error {
	return dao.InitTables(db)
}
