// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"context"
	"gitee.com/flycash/notification-platform/internal/api/grpc"
	"gitee.com/flycash/notification-platform/internal/domain"
	"gitee.com/flycash/notification-platform/internal/ioc"
	"gitee.com/flycash/notification-platform/internal/repository"
	"gitee.com/flycash/notification-platform/internal/repository/cache/local"
	"gitee.com/flycash/notification-platform/internal/repository/cache/redis"
	"gitee.com/flycash/notification-platform/internal/repository/dao"
	"gitee.com/flycash/notification-platform/internal/service/audit"
	"gitee.com/flycash/notification-platform/internal/service/channel"
	"gitee.com/flycash/notification-platform/internal/service/config"
	"gitee.com/flycash/notification-platform/internal/service/notification"
	"gitee.com/flycash/notification-platform/internal/service/notification/callback"
	"gitee.com/flycash/notification-platform/internal/service/provider"
	"gitee.com/flycash/notification-platform/internal/service/provider/manage"
	"gitee.com/flycash/notification-platform/internal/service/provider/sequential"
	"gitee.com/flycash/notification-platform/internal/service/provider/sms"
	"gitee.com/flycash/notification-platform/internal/service/provider/sms/client"
	"gitee.com/flycash/notification-platform/internal/service/send_strategy"
	"gitee.com/flycash/notification-platform/internal/service/sender"
	manage2 "gitee.com/flycash/notification-platform/internal/service/template/manage"
	"github.com/google/wire"
	"time"
)

// Injectors from wire.go:

func newSendStrategy(repo repository.NotificationRepository, configSvc config.BusinessConfigService, sender2 sender.NotificationSender) send_strategy.SendStrategy {
	immediateSendStrategy := send_strategy.NewImmediateStrategy(repo, sender2)
	defaultSendStrategy := send_strategy.NewDefaultStrategy(repo, configSvc)
	sendStrategy := send_strategy.NewDispatcher(immediateSendStrategy, defaultSendStrategy)
	return sendStrategy
}

func InitGrpcServer() *ioc.App {
	db := ioc.InitDB()
	channelTemplateDAO := dao.NewChannelTemplateDAO(db)
	channelTemplateRepository := repository.NewChannelTemplateRepository(channelTemplateDAO)
	string2 := ioc.InitProviderEncryptKey()
	providerDAO := dao.NewProviderDAO(db, string2)
	providerRepository := repository.NewProviderRepository(providerDAO)
	service := manage.NewProviderService(providerRepository)
	auditService := audit.NewService()
	channelTemplateService := manage2.NewChannelTemplateService(channelTemplateRepository, service, auditService)
	notificationDAO := dao.NewNotificationDAO(db)
	notificationRepository := repository.NewNotificationRepository(notificationDAO)
	sonyflake := ioc.InitIDGenerator()
	notificationService := notification.NewNotificationService(notificationRepository, sonyflake)
	businessConfigDAO := dao.NewBusinessConfigDAO(db)
	client := ioc.InitRedis()
	cache := ioc.InitGoCache()
	localCache := local.NewLocalCache(client, cache)
	redisCache := redis.NewCache(client)
	businessConfigRepository := repository.NewBusinessConfigRepository(businessConfigDAO, localCache, redisCache)
	businessConfigService := config.NewBusinessConfigService(businessConfigRepository)
	callbackLogDAO := dao.NewCallbackLogDAO(db)
	callbackLogRepository := repository.NewCallbackLogRepository(notificationRepository, callbackLogDAO)
	callbackService := callback.NewService(businessConfigService, callbackLogRepository)
	v := ioc.InitSmsClients()
	channel := newChannel(service, channelTemplateService, v)
	notificationSender := sender.NewSender(notificationRepository, businessConfigService, callbackService, channel)
	sendStrategy := newSendStrategy(notificationRepository, businessConfigService, notificationSender)
	sendService := notification.NewSendService(channelTemplateService, notificationService, sonyflake, sendStrategy)
	txNotificationDAO := dao.NewTxNotificationDAO(db)
	txNotificationRepository := repository.NewTxNotificationRepository(txNotificationDAO)
	dlockClient := ioc.InitDLock()
	txNotificationService := notification.NewTxNotificationService(txNotificationRepository, businessConfigService, notificationRepository, dlockClient)
	notificationServer := grpc.NewServer(sendService, txNotificationService)
	component := ioc.InitEtcdClient()
	egrpcComponent := ioc.InitGrpc(notificationServer, component)
	app := &ioc.App{
		GrpcServer: egrpcComponent,
	}
	return app
}

// wire.go:

var (
	BaseSet              = wire.NewSet(ioc.InitDB, ioc.InitDLock, ioc.InitEtcdClient, ioc.InitIDGenerator, ioc.InitRedis, ioc.InitSmsClients, ioc.InitGoCache, local.NewLocalCache, redis.NewCache)
	configSvcSet         = wire.NewSet(config.NewBusinessConfigService, repository.NewBusinessConfigRepository, dao.NewBusinessConfigDAO)
	notificationSvcSet   = wire.NewSet(notification.NewNotificationService, repository.NewNotificationRepository, dao.NewNotificationDAO)
	txNotificationSvcSet = wire.NewSet(notification.NewTxNotificationService, repository.NewTxNotificationRepository, dao.NewTxNotificationDAO)
	senderSvcSet         = wire.NewSet(
		newChannel, sender.NewSender,
	)
	sendNotificationSvcSet = wire.NewSet(notification.NewSendService, newSendStrategy)
	callbackSvcSet         = wire.NewSet(callback.NewService, repository.NewCallbackLogRepository, dao.NewCallbackLogDAO)
	providerSvcSet         = wire.NewSet(manage.NewProviderService, repository.NewProviderRepository, dao.NewProviderDAO, ioc.InitProviderEncryptKey)
	templateSvcSet         = wire.NewSet(manage2.NewChannelTemplateService, repository.NewChannelTemplateRepository, dao.NewChannelTemplateDAO)
)

func newChannel(
	providerSvc manage.Service,
	templateSvc manage2.ChannelTemplateService,
	clients map[string]client.Client,
) channel.Channel {
	return channel.NewDispatcher(map[domain.Channel]channel.Channel{domain.ChannelEmail: channel.NewSMSChannel(newSMSSelectorBuilder(providerSvc, templateSvc, clients))})
}

func newSMSSelectorBuilder(
	providerSvc manage.Service,
	templateSvc manage2.ChannelTemplateService,
	clients map[string]client.Client,
) *sequential.SelectorBuilder {
	providers := initSMSProviders(providerSvc, templateSvc, clients)
	return sequential.NewSelectorBuilder(providers)
}

func initSMSProviders(
	providerSvc manage.Service,
	templateSvc manage2.ChannelTemplateService,
	clients map[string]client.Client,
) []provider.Provider {

	ctx, cancelFunc := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancelFunc()

	entities, err := providerSvc.GetProvidersByChannel(ctx, domain.ChannelSMS)
	if err != nil {
		panic(err)
	}
	providers := make([]provider.Provider, 0, len(entities))
	for i := range entities {
		providers = append(providers, sms.NewSMSProvider(
			entities[i].Name,
			templateSvc,
			clients[entities[i].Name],
		))
	}
	return providers
}
