// Code generated by MockGen. DO NOT EDIT.
// Source: ./config.go
//
// Generated by this command:
//
//	mockgen -source=./config.go -destination=../../mocks/config.mock.go -package=configmocks -typed BusinessConfigService
//

// Package configmocks is a generated GoMock package.
package configmocks

import (
	context "context"
	"gitee.com/flycash/notification-platform/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBusinessConfigService is a mock of BusinessConfigService interface.
type MockBusinessConfigService struct {
	ctrl     *gomock.Controller
	recorder *MockBusinessConfigServiceMockRecorder
	isgomock struct{}
}

// MockBusinessConfigServiceMockRecorder is the mock recorder for MockBusinessConfigService.
type MockBusinessConfigServiceMockRecorder struct {
	mock *MockBusinessConfigService
}

// NewMockBusinessConfigService creates a new mock instance.
func NewMockBusinessConfigService(ctrl *gomock.Controller) *MockBusinessConfigService {
	mock := &MockBusinessConfigService{ctrl: ctrl}
	mock.recorder = &MockBusinessConfigServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBusinessConfigService) EXPECT() *MockBusinessConfigServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockBusinessConfigService) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBusinessConfigServiceMockRecorder) Delete(ctx, id any) *MockBusinessConfigServiceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBusinessConfigService)(nil).Delete), ctx, id)
	return &MockBusinessConfigServiceDeleteCall{Call: call}
}

// MockBusinessConfigServiceDeleteCall wrap *gomock.Call
type MockBusinessConfigServiceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBusinessConfigServiceDeleteCall) Return(arg0 error) *MockBusinessConfigServiceDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBusinessConfigServiceDeleteCall) Do(f func(context.Context, int64) error) *MockBusinessConfigServiceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBusinessConfigServiceDeleteCall) DoAndReturn(f func(context.Context, int64) error) *MockBusinessConfigServiceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockBusinessConfigService) GetByID(ctx context.Context, id int64) (domain.BusinessConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.BusinessConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBusinessConfigServiceMockRecorder) GetByID(ctx, id any) *MockBusinessConfigServiceGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBusinessConfigService)(nil).GetByID), ctx, id)
	return &MockBusinessConfigServiceGetByIDCall{Call: call}
}

// MockBusinessConfigServiceGetByIDCall wrap *gomock.Call
type MockBusinessConfigServiceGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBusinessConfigServiceGetByIDCall) Return(arg0 domain.BusinessConfig, arg1 error) *MockBusinessConfigServiceGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBusinessConfigServiceGetByIDCall) Do(f func(context.Context, int64) (domain.BusinessConfig, error)) *MockBusinessConfigServiceGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBusinessConfigServiceGetByIDCall) DoAndReturn(f func(context.Context, int64) (domain.BusinessConfig, error)) *MockBusinessConfigServiceGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByIDs mocks base method.
func (m *MockBusinessConfigService) GetByIDs(ctx context.Context, ids []int64) (map[int64]domain.BusinessConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].(map[int64]domain.BusinessConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockBusinessConfigServiceMockRecorder) GetByIDs(ctx, ids any) *MockBusinessConfigServiceGetByIDsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockBusinessConfigService)(nil).GetByIDs), ctx, ids)
	return &MockBusinessConfigServiceGetByIDsCall{Call: call}
}

// MockBusinessConfigServiceGetByIDsCall wrap *gomock.Call
type MockBusinessConfigServiceGetByIDsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBusinessConfigServiceGetByIDsCall) Return(arg0 map[int64]domain.BusinessConfig, arg1 error) *MockBusinessConfigServiceGetByIDsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBusinessConfigServiceGetByIDsCall) Do(f func(context.Context, []int64) (map[int64]domain.BusinessConfig, error)) *MockBusinessConfigServiceGetByIDsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBusinessConfigServiceGetByIDsCall) DoAndReturn(f func(context.Context, []int64) (map[int64]domain.BusinessConfig, error)) *MockBusinessConfigServiceGetByIDsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveConfig mocks base method.
func (m *MockBusinessConfigService) SaveConfig(ctx context.Context, config domain.BusinessConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveConfig", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveConfig indicates an expected call of SaveConfig.
func (mr *MockBusinessConfigServiceMockRecorder) SaveConfig(ctx, config any) *MockBusinessConfigServiceSaveConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveConfig", reflect.TypeOf((*MockBusinessConfigService)(nil).SaveConfig), ctx, config)
	return &MockBusinessConfigServiceSaveConfigCall{Call: call}
}

// MockBusinessConfigServiceSaveConfigCall wrap *gomock.Call
type MockBusinessConfigServiceSaveConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBusinessConfigServiceSaveConfigCall) Return(arg0 error) *MockBusinessConfigServiceSaveConfigCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBusinessConfigServiceSaveConfigCall) Do(f func(context.Context, domain.BusinessConfig) error) *MockBusinessConfigServiceSaveConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBusinessConfigServiceSaveConfigCall) DoAndReturn(f func(context.Context, domain.BusinessConfig) error) *MockBusinessConfigServiceSaveConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
