mysql:
  dsn: "root:root@tcp(localhost:13316)/notification?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=1s&readTimeout=3s&writeTimeout=3s&multiStatements=true"

redis:
  addr: "localhost:6379"

etcd:
  addrs:
    - "127.0.0.1:2379"
  connectTimeout: "1s"
  secure: false
server:
  governor:
    host: 0.0.0.0
    port: 9003
  grpc:
    host: "0.0.0.0"
    port: 9002

provider:
  key: "test_key"
cache:
  defaultExpiration: 60000000000
  cleanupInterval: 60000000000

trace:
  zipkin:
    endpoint: "http://localhost:9411/api/v2/spans"
    serviceName: "notification-platform"


jwt:
  key: "test_key"