mysql:
  dsn: "root:root@tcp(localhost:13316)/notification?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=1s&readTimeout=3s&writeTimeout=3s&multiStatements=true"

redis:
  addr: "localhost:6379"

etcd:
  addrs:
    - "127.0.0.1:2379"
  connectTimeout: "1s"
  secure: false
server:
  grpc:
    host: "127.0.0.1"
    port: 9002

provider:
  key: "test_key"
cache:
  defaultExpiration: 60000000000
  cleanupInterval: 60000000000
