// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"gitee.com/flycash/notification-platform/internal/repository"
	"gitee.com/flycash/notification-platform/internal/repository/cache/local"
	"gitee.com/flycash/notification-platform/internal/repository/cache/redis"
	"gitee.com/flycash/notification-platform/internal/repository/dao"
	"gitee.com/flycash/notification-platform/internal/service/config"
	"gitee.com/flycash/notification-platform/internal/test/ioc"
	"github.com/patrickmn/go-cache"
)

// Injectors from wire.go:

func InitConfigService(localCache *cache.Cache) *config.BusinessConfigServiceV1 {
	v := ioc.InitDB()
	businessConfigDAO := dao.NewBusinessConfigDAO(v)
	client := ioc.InitRedisClient()
	cache2 := local.NewLocalCache(client, localCache)
	redisCache := redis.NewCache(client)
	businessConfigRepository := repository.NewBusinessConfigRepository(businessConfigDAO, cache2, redisCache)
	businessConfigServiceV1 := config.NewBusinessConfigService(businessConfigRepository)
	return businessConfigServiceV1
}
