// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package audit

// Injectors from wire.go:

func InitMoudle() *Module {
	module := InitAudit()
	return module
}

// wire.go:

func InitAudit() *Module {
	return &Module{
		Svc: nil,
	}
}
