// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"gitee.com/flycash/notification-platform/internal/service/config"
	"gitee.com/flycash/notification-platform/internal/service/executor"
	"gitee.com/flycash/notification-platform/internal/service/executor/internal/service"
	"gitee.com/flycash/notification-platform/internal/service/notification"
	"gitee.com/flycash/notification-platform/internal/service/pkg/client/sms"
	"gitee.com/flycash/notification-platform/internal/service/provider"
	"gitee.com/flycash/notification-platform/internal/service/template"
	"gitee.com/flycash/notification-platform/internal/test/ioc"
)

// Injectors from wire.go:

func InitService(notificationSvc notification.Service, configSvc config.Service, providerSvc provider.Service, templateSvc template.Service, smsClients map[string]sms.Client) service.ExecutorService {
	sonyflake := ioc.InitIDGenerator()
	module := executor.InitModule(sonyflake, notificationSvc, configSvc, providerSvc, templateSvc, smsClients)
	executorService := module.Svc
	return executorService
}
