// Code generated by MockGen. DO NOT EDIT.
// Source: ./producer.go
//
// Generated by this command:
//
//	mockgen -source=./producer.go -package=evtmocks -destination=../mocks/ratelimit_event_producer.mock.go -typed RequestRateLimitedEventProducer
//

// Package evtmocks is a generated GoMock package.
package evtmocks

import (
	context "context"
	reflect "reflect"

	ratelimit "gitee.com/flycash/notification-platform/internal/event/ratelimit"
	gomock "go.uber.org/mock/gomock"
)

// MockRequestRateLimitedEventProducer is a mock of RequestRateLimitedEventProducer interface.
type MockRequestRateLimitedEventProducer struct {
	ctrl     *gomock.Controller
	recorder *MockRequestRateLimitedEventProducerMockRecorder
	isgomock struct{}
}

// MockRequestRateLimitedEventProducerMockRecorder is the mock recorder for MockRequestRateLimitedEventProducer.
type MockRequestRateLimitedEventProducerMockRecorder struct {
	mock *MockRequestRateLimitedEventProducer
}

// NewMockRequestRateLimitedEventProducer creates a new mock instance.
func NewMockRequestRateLimitedEventProducer(ctrl *gomock.Controller) *MockRequestRateLimitedEventProducer {
	mock := &MockRequestRateLimitedEventProducer{ctrl: ctrl}
	mock.recorder = &MockRequestRateLimitedEventProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestRateLimitedEventProducer) EXPECT() *MockRequestRateLimitedEventProducerMockRecorder {
	return m.recorder
}

// Produce mocks base method.
func (m *MockRequestRateLimitedEventProducer) Produce(ctx context.Context, evt ratelimit.RequestRateLimitedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Produce", ctx, evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Produce indicates an expected call of Produce.
func (mr *MockRequestRateLimitedEventProducerMockRecorder) Produce(ctx, evt any) *MockRequestRateLimitedEventProducerProduceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockRequestRateLimitedEventProducer)(nil).Produce), ctx, evt)
	return &MockRequestRateLimitedEventProducerProduceCall{Call: call}
}

// MockRequestRateLimitedEventProducerProduceCall wrap *gomock.Call
type MockRequestRateLimitedEventProducerProduceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRequestRateLimitedEventProducerProduceCall) Return(arg0 error) *MockRequestRateLimitedEventProducerProduceCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRequestRateLimitedEventProducerProduceCall) Do(f func(context.Context, ratelimit.RequestRateLimitedEvent) error) *MockRequestRateLimitedEventProducerProduceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRequestRateLimitedEventProducerProduceCall) DoAndReturn(f func(context.Context, ratelimit.RequestRateLimitedEvent) error) *MockRequestRateLimitedEventProducerProduceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
