// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"gitee.com/flycash/notification-platform/internal/service/provider"
	"gitee.com/flycash/notification-platform/internal/test/ioc"
)

// Injectors from wire.go:

func InitProviderService() provider.Service {
	db := ioc.InitDB()
	string2 := encryptKey()
	module := provider.InitModule(db, string2)
	service := module.Svc
	return service
}

// wire.go:

func encryptKey() string {
	return "wire1234567890abcdefgh337ywz790"
}
