// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package notification

import (
	"gitee.com/flycash/notification-platform/internal/repository"
	dao2 "gitee.com/flycash/notification-platform/internal/repository/dao"
	"gitee.com/flycash/notification-platform/internal/service/notification/internal/repository/dao"
	"gitee.com/flycash/notification-platform/internal/service/notification/internal/service"
	"github.com/ego-component/egorm"
	"github.com/google/wire"
	"github.com/sony/sonyflake"
)

// Injectors from wire.go:

func InitModule(db *egorm.Component, idGenerator *sonyflake.Sonyflake) Module {
	error2 := initTables(db)
	notificationDAO := dao2.NewNotificationDAO(db)
	notificationRepository := repository.NewNotificationRepository(notificationDAO)
	notificationService := service.NewNotificationService(notificationRepository, idGenerator)
	service2 := convert(notificationService)
	module := Module{
		ignoredInitTablesErr: error2,
		Svc:                  service2,
	}
	return module
}

// wire.go:

var notificationServiceProviderSet = wire.NewSet(dao2.NewNotificationDAO, repository.NewNotificationRepository, service.NewNotificationService)

func convert(svc service.NotificationService) Service {
	return svc.(Service)
}

func initTables(db *egorm.Component) error {
	return dao.InitTables(db)
}
