// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"gitee.com/flycash/notification-platform/internal/service/config/internal/repository"
	"gitee.com/flycash/notification-platform/internal/service/config/internal/repository/dao"
	"gitee.com/flycash/notification-platform/internal/service/config/internal/service"
	"github.com/ego-component/egorm"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitService(db *gorm.DB) *Module {
	error2 := initTables(db)
	businessConfigDAO := dao.NewBusinessConfigDAO(db)
	businessConfigRepository := repository.NewBusinessConfigRepository(businessConfigDAO)
	businessConfigService := service.NewBusinessConfigService(businessConfigRepository)
	module := &Module{
		ignoredInitTablesErr: error2,
		Svc:                  businessConfigService,
	}
	return module
}

// wire.go:

func initTables(db *egorm.Component) error {
	return dao.InitTables(db)
}
